---
title: "p8105_hw3_ew2717"
author: "Eric Wang"
output: github_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

```


```{r}

library(tidyverse)
library(patchwork)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Problem 1

#### Loading instacart data

```{r}

data("instacart")

instacart_df <-
  instacart %>% 
  janitor::clean_names()

```

## PROBLEM 1

#### Loading instacart dataset

```{r load instacard data}
data("instacart")
instacart_df <- 
  instacart %>% 
  janitor::clean_names()
```
### Instacard data exploration 

```{r intstacart data exploration}

instacart_rows = instacart_df %>% nrow()
instacart_cols = instacart_df %>% ncol()
instacart_names = instacart_df %>% names()

```

The number of rows in the instacart data set is **`r instacart_rows`**. The number of columns in the instacart data set is **`r instacart_cols`**. The key variables in the instacart data set are **`r instacart_names`**.

